import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './api/auth/Providers'
import NavBar from './components/NavBar'
import { Toaster } from "react-hot-toast"
import SideBare from './components/mainPage/SideBare'
import Latest from './components/mainPage/Latest'
import Banner from './components/mainPage/Banner'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <main className='p-5 grid container mx-auto grid-cols-4 gap-6'>
            <SideBare />
            <section className="col-span-2">

              <Banner />
              {children}
            </section>
            <Latest />
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
