import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './api/auth/Providers'
import NavBar from './components/NavBar'
import { Toaster } from "react-hot-toast"
import SideBare from './components/mainPage/SideBare'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ewa Comm²',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <main className='p-5  grid container mx-auto grid-cols-4 gap-6'>
            <div className='col-span-1 '>
              <SideBare />
            </div>
            <section className="col-span-3 ">
              {/* <Banner /> */}
              {children}
            </section>

          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
