import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './api/auth/Providers'
import NavBar from './components/NavBar'
import { Toaster } from "react-hot-toast"
import SideBare from './components/mainPage/SideBare'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ewa Com²',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <main className=''>
            {children}
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
